### ISSUE TITLE
self.modeladmin returns null

### ISSUE THREAD

**Issue by czechmate247** [praekelt/django-object-tools#39]
When following your tutorial, I keep getting the error when executing this line:

`return self.modeladmin.changelist_view(request)`

The error I get is:

**AttributeError: 'NoneType' object has no attribute 'changelist_view'**

But when I used the code below, everything worked fine:

```
from django.contrib.admin import site
...
return site._registry(self.model).changelist_view(request)
```

It seems like the **self.modeladmin** is not getting populated correctly.  My workaround appears to suffice for now but I just wanted to make you aware of what I found.

**Comment by cblignaut** [comment]
Thanks a lot, the example was updated.
